
package proxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ReleveWS", targetNamespace = "http://IIBDCC.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReleveWS {


    /**
     * 
     * @return
     *     returns proxy.Releve
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReleve", targetNamespace = "http://IIBDCC.ma/", className = "proxy.GetReleve")
    @ResponseWrapper(localName = "getReleveResponse", targetNamespace = "http://IIBDCC.ma/", className = "proxy.GetReleveResponse")
    @Action(input = "http://IIBDCC.ma/ReleveWS/getReleveRequest", output = "http://IIBDCC.ma/ReleveWS/getReleveResponse")
    public Releve getReleve();

}
